package com.example.indoorview;

public class MapaEventoActivity {
    // AQUI SE HARA LO DE PUNTO EXACTO DEL EVENTO SOLO DE REFERENCIA
    // COMO TAMBIEN LO QUE SERIA MOSTRAR EL PUNTO DE UN EVENTO SELECIONADO
    // TODO CON IDENT DE INFORMACION O UN JSON OBJECT QUE SE UTILIZARA PARA EL PIN
    // CADA PIN TENDRA UN COLOR EN COMUN Y NO PODRA MODIFICARSE DEMASIADO
}
